---
- name: KLineBuildWorker
  exchange: quote.default
  routing_key: quote.kLine.build
  queue: quote.kLine.build
  log: logs/k.log
  durable: true
  threads: 2

- name: SubQuoteBuildWorker
  exchange: quote.default
  routing_key: quote.sub.build
  queue: quote.sub.build
  log: logs/quote.log
  durable: true
  threads: 8